version: "3"

volumes:
  local-postgres-data: {}
  local-redis-data: {}

services:
  django:
    build:
      context: .
      dockerfile: ./.docker/django/Dockerfile
    image: consultas_ciudadanas_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    ports:
      - 8000:8000
    command:
      - runserver

  postgres:
    image: postgis/postgis:16-3.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - local-postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - 6379:6379
    volumes:
      - local-redis-data:/data

  node:
    build:
      context: .
      dockerfile: ./.docker/node/Dockerfile
    image: consultas_ciudadanas_node
    volumes:
      - .:/app:z
      - /app/node_modules
    command: npm run dev
    ports:
      - 3000:3000
      - 3001:3001
