# Generated by Django 4.1 on 2024-01-04 22:03

import apps.utils.random
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import functools
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AllowedResponder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email_code",
                    models.CharField(
                        default=functools.partial(
                            apps.utils.random.get_random_url_code, *(), **{"size": 15}
                        ),
                        max_length=15,
                        unique=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PublicQuery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("OPEN", "Abierta"), ("CLOSED", "Cerrada")],
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("start_at", models.DateTimeField(blank=True, null=True)),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                ("active", models.BooleanField(default=False)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="public_queries/images/"
                    ),
                ),
                (
                    "url_code",
                    models.CharField(
                        default=apps.utils.random.get_random_url_code,
                        max_length=15,
                        unique=True,
                    ),
                ),
                ("max_responses", models.PositiveIntegerField(default=0)),
                (
                    "auth_rut",
                    models.CharField(
                        choices=[
                            ("REQUIRED", "Requerido"),
                            ("OPTIONAL", "Opcional"),
                            ("DISABLE", "Deshabilitado"),
                        ],
                        default="OPTIONAL",
                        max_length=50,
                    ),
                ),
                (
                    "auth_email",
                    models.CharField(
                        choices=[
                            ("REQUIRED", "Requerido"),
                            ("OPTIONAL", "Opcional"),
                            ("DISABLE", "Deshabilitado"),
                        ],
                        default="OPTIONAL",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Consulta",
                "verbose_name_plural": "Consultas",
                "ordering": ["start_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text"),
                            ("IMAGE", "Image"),
                            ("SELECT", "Select"),
                            ("POINT", "Geo Point"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("order", models.IntegerField(default=0)),
                ("required", models.BooleanField(default=True)),
                ("text_max_length", models.IntegerField(default=255)),
                ("max_answers", models.IntegerField(default=1)),
                ("min_answers", models.PositiveIntegerField(default=1)),
                (
                    "query",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="public_queries.publicquery",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pregunta",
                "verbose_name_plural": "Preguntas",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Responder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254)),
            ],
            options={
                "verbose_name": "Pregunta",
                "verbose_name_plural": "Preguntas",
                "ordering": ["email"],
            },
        ),
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("send_at", models.DateTimeField()),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("rut", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "allowed_responder",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="public_queries.allowedresponder",
                    ),
                ),
                (
                    "query",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="public_queries.publicquery",
                    ),
                ),
            ],
            options={
                "verbose_name": "Respuesta",
                "verbose_name_plural": "Respuestas",
                "ordering": ["send_at"],
            },
        ),
        migrations.CreateModel(
            name="QuestionOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("order", models.IntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="public_queries.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opción",
                "verbose_name_plural": "Opciones",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="publicquery",
            name="allowed_responders",
            field=models.ManyToManyField(
                through="public_queries.AllowedResponder", to="public_queries.responder"
            ),
        ),
        migrations.AddField(
            model_name="publicquery",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="public_queries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="public_queries/answers/images/",
                    ),
                ),
                (
                    "point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "options",
                    models.ManyToManyField(
                        limit_choices_to=models.Q(
                            ("question_id", models.F("question_id"))
                        ),
                        related_name="answers",
                        to="public_queries.questionoption",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="public_queries.question",
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="public_queries.response",
                    ),
                ),
            ],
            options={
                "verbose_name": "Respuesta a pregunta",
                "verbose_name_plural": "Respuestas a preguntas",
                "ordering": ["question__order"],
            },
        ),
        migrations.AddField(
            model_name="allowedresponder",
            name="query",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="public_queries.publicquery",
            ),
        ),
        migrations.AddField(
            model_name="allowedresponder",
            name="responder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="public_queries.responder",
            ),
        ),
    ]
