# Generated by Django 4.2.7 on 2023-11-23 01:57

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_queries", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="response",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
