# Generated by Django 4.2.7 on 2023-11-27 14:04

import apps.utils.random
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_queries", "0002_alter_response_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicquery",
            name="url_code",
            field=models.CharField(
                default=apps.utils.random.get_random_url_code,
                max_length=15,
                null=True,
            ),
        ),
    ]
