# Generated by Django 4.2.7 on 2023-11-27 14:04

from django.db import migrations
from apps.utils.random import get_random_url_code


def populate_url_code(apps, schema_editor) -> None:
    PublicQuery = apps.get_model("public_queries", "PublicQuery")
    updated_instances = []
    for query in PublicQuery.objects.all():
        query.url_code = get_random_url_code()
        updated_instances.append(query)
    PublicQuery.objects.bulk_update(objs=updated_instances, fields=["url_code"])


class Migration(migrations.Migration):
    dependencies = [
        ("public_queries", "0003_publicquery_url_code"),
    ]

    operations = [
        migrations.RunPython(
            populate_url_code, reverse_code=migrations.RunPython.noop
        )
    ]
