# Generated by Django 4.2.7 on 2023-11-27 14:04

from django.db import migrations, models

import apps.utils.random


class Migration(migrations.Migration):
    dependencies = [
        ("public_queries", "0004_populate_url_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicquery",
            name="url_code",
            field=models.CharField(
                default=apps.utils.random.get_random_url_code,
                max_length=15,
                unique=True,
            ),
        ),

    ]
