# Generated by Django 4.2.7 on 2023-11-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_queries", "0005_remove_url_code_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="public_queries/answers/images/"
            ),
        ),
        migrations.AlterField(
            model_name="publicquery",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="public_queries/images/"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="kind",
            field=models.CharField(choices=[("TEXT", "Text"), ("IMAGE", "Image")]),
        ),
        migrations.AlterField(
            model_name="question",
            name="max_answers",
            field=models.IntegerField(default=1),
        ),
    ]
