# Generated by Django 4.2.7 on 2023-11-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_queries", "0007_alter_question_kind_questionoption_answer_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="questionoption",
            options={"ordering": ["order"]},
        ),
        migrations.AlterField(
            model_name="answer",
            name="options",
            field=models.ManyToManyField(
                limit_choices_to=models.Q(("question_id", models.F("question_id"))),
                related_name="answers",
                to="public_queries.questionoption",
            ),
        ),
    ]
