# Generated by Django 4.2.7 on 2023-12-04 21:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_queries", "0008_alter_questionoption_options_alter_answer_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="point",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="kind",
            field=models.CharField(
                choices=[
                    ("TEXT", "Text"),
                    ("IMAGE", "Image"),
                    ("SELECT", "Select"),
                    ("POINT", "Geo Point"),
                ]
            ),
        ),
    ]
