# Generated by Django 4.2.7 on 2023-12-28 16:05

import apps.utils.random
from django.db import migrations, models
import django.db.models.deletion
import functools
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("public_queries", "0009_answer_point_alter_question_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="Responder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254)),
            ],
            options={
                "verbose_name": "Pregunta",
                "verbose_name_plural": "Preguntas",
                "ordering": ["email"],
            },
        ),
        migrations.AlterModelOptions(
            name="answer",
            options={
                "ordering": ["question__order"],
                "verbose_name": "Respuesta a pregunta",
                "verbose_name_plural": "Respuestas a preguntas",
            },
        ),
        migrations.AlterModelOptions(
            name="publicquery",
            options={
                "ordering": ["start_at"],
                "verbose_name": "Consulta",
                "verbose_name_plural": "Consultas",
            },
        ),
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ["order"],
                "verbose_name": "Pregunta",
                "verbose_name_plural": "Preguntas",
            },
        ),
        migrations.AlterModelOptions(
            name="questionoption",
            options={
                "ordering": ["order"],
                "verbose_name": "Opción",
                "verbose_name_plural": "Opciones",
            },
        ),
        migrations.AlterModelOptions(
            name="response",
            options={
                "ordering": ["send_at"],
                "verbose_name": "Respuesta",
                "verbose_name_plural": "Respuestas",
            },
        ),
        migrations.AddField(
            model_name="publicquery",
            name="max_responses",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="question",
            name="min_answers",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="publicquery",
            name="kind",
            field=models.CharField(
                choices=[("OPEN", "Abierta"), ("CLOSED", "Cerrada")]
            ),
        ),
        migrations.CreateModel(
            name="AllowedResponder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email_code",
                    models.CharField(
                        default=functools.partial(
                            apps.utils.random.get_random_url_code, *(), **{"size": 15}
                        ),
                        max_length=15,
                        unique=True,
                    ),
                ),
                (
                    "query",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="public_queries.publicquery",
                    ),
                ),
                (
                    "responder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="public_queries.responder",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="publicquery",
            name="allowed_responders",
            field=models.ManyToManyField(
                through="public_queries.AllowedResponder", to="public_queries.responder"
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="allowed_responder",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="public_queries.allowedresponder",
            ),
        ),
    ]
