# Generated by Django 4.2.7 on 2023-12-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_queries", "0010_responder_alter_answer_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicquery",
            name="auth_email",
            field=models.CharField(
                choices=[
                    ("REQUIRED", "Requerido"),
                    ("OPTIONAL", "Opcional"),
                    ("DISABLE", "Deshabilitado"),
                ],
                default="OPTIONAL",
            ),
        ),
        migrations.AddField(
            model_name="publicquery",
            name="auth_rut",
            field=models.CharField(
                choices=[
                    ("REQUIRED", "Requerido"),
                    ("OPTIONAL", "Opcional"),
                    ("DISABLE", "Deshabilitado"),
                ],
                default="OPTIONAL",
            ),
        ),
    ]
