# Generated by Django 4.2.7 on 2024-01-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_queries", "0011_publicquery_auth_email_publicquery_auth_rut"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicquery",
            name="auth_email",
            field=models.CharField(
                choices=[
                    ("REQUIRED", "Requerido"),
                    ("OPTIONAL", "Opcional"),
                    ("DISABLE", "Deshabilitado"),
                ],
                default="OPTIONAL",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="publicquery",
            name="auth_rut",
            field=models.CharField(
                choices=[
                    ("REQUIRED", "Requerido"),
                    ("OPTIONAL", "Opcional"),
                    ("DISABLE", "Deshabilitado"),
                ],
                default="OPTIONAL",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="publicquery",
            name="kind",
            field=models.CharField(
                choices=[("OPEN", "Abierta"), ("CLOSED", "Cerrada")], max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="kind",
            field=models.CharField(
                choices=[
                    ("TEXT", "Text"),
                    ("IMAGE", "Image"),
                    ("SELECT", "Select"),
                    ("POINT", "Geo Point"),
                ],
                max_length=200,
            ),
        ),
    ]
