# Generated by Django 4.2.7 on 2024-03-27 14:52

import apps.public_queries.storages
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_queries", "0012_alter_publicquery_auth_email_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="responder",
            options={
                "ordering": ["email"],
                "verbose_name": "Consultado",
                "verbose_name_plural": "Consultados",
            },
        ),
        migrations.AddField(
            model_name="answer",
            name="line",
            field=django.contrib.gis.db.models.fields.LineStringField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.public_queries.storages.get_public_query_question_image_path,
            ),
        ),
        migrations.AddField(
            model_name="questionoption",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.public_queries.storages.get_public_query_question_option_image_path,
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.public_queries.storages.get_public_query_answer_image_path,
            ),
        ),
        migrations.AlterField(
            model_name="publicquery",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.public_queries.storages.get_public_query_image_path,
            ),
        ),
    ]
