# Generated by Django 4.2.7 on 2024-05-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "public_queries",
            "0013_alter_responder_options_answer_line_question_image_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="visible",
            field=models.BooleanField(default=True),
        ),
    ]
