# Generated by Django 4.2.7 on 2024-05-22 21:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_queries", "0014_response_visible"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="default_point",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="default_zoom",
            field=models.IntegerField(null=True),
        ),
    ]
