# Generated by Django 4.2.7 on 2024-06-12 17:57

import apps.public_queries.storages
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_queries", "0015_question_default_point_question_default_zoom"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="thumb",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.public_queries.storages.get_public_query_answer_image_path_thumb,
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="thumb_medium",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.public_queries.storages.get_public_query_answer_image_path_thumb_medium,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="kind",
            field=models.CharField(
                choices=[
                    ("TEXT", "Text"),
                    ("IMAGE", "Image"),
                    ("SELECT", "Select"),
                    ("SELECT_IMAGE", "Select images"),
                    ("POINT", "Geo Point"),
                ],
                max_length=200,
            ),
        ),
    ]
