#!/usr/bin/env bash
set -euo pipefail

_usage() {
  echo "running the dev server"
  echo "    up/run        start the server in development mode"
  echo "    celery    run a celery worker"
  echo "    beat      run celery beat scheduler"
  echo ""
  echo "testing"
  echo "    test      run tests, accepts arguments"
  echo "    cov       run tests with coverage"
  echo "    cov-report generate a HTML coverage report"
  echo ""
  echo "installing Python requirements"
  echo "    pipi      without argument: installs packages defined in requirements.txt and requirements-local.txt"
  echo "              with argument:    installs given requirement"
  echo ""
  echo "migrations"
  echo "    migrate   run pending migrations"
  echo "    makemig   make Django migrations"
  echo "    sqlmig    show SQL of migration without executing it"
  echo ""
  echo "tools"
  echo "    black     run black"
  echo "    isort     run isort"
  exit 1
}

# show usage if no argument is given
arg=${1:-}
shift || _usage

case ${arg} in
up|run)
  python manage.py runserver 0.0.0.0:8000
;;
celery)
  celery -A config.celery_app worker -c 1 -l DEBUG
;;
beat)
  celery -A config.celery_app beat -l DEBUG 
;;
test)
  pytest "$@" --junitxml=/dev/shm/test-results/pytest.xml
;;
cov)
  pytest "$@" --cov=apps --cov-report=term-missing --cov-fail-under=95 --junitxml=/dev/shm/test-results/pytest.xml
;;
cov-report)
  pytest "$@" --cov=apps --cov-report=html --junitxml=/dev/shm/test-results/pytest.xml
  echo "HTML Report: ./htmlcov/index.html"
;;
isort)
  isort .
;;
black)
  black .
;;
pipi)
  if [ $# -gt 0 ]; then
    pip install --no-warn-script-location \
      --disable-pip-version-check \
      --no-cache-dir \
      --user "$@"
  else
    pip install --no-warn-script-location \
      --disable-pip-version-check \
      --no-cache-dir \
      --user \
      -r /app/requirements/${ENVIROMENT}.txt
  fi
;;
migrate)
  python manage.py migrate "$@"
;;
makemigrations|makemigration|makemig)
  python manage.py makemigrations "$@"
;;
sqlmig|sqlmigrate|sqlmigration)
  python manage.py sqlmigrate "$@"
;;
makemessages|mkmsgs)
  python manage.py makemessages "$@"
;;
compilemessages|cmplmsgs)
  python manage.py compilemessages "$@"
;;
createsuperuser|createroot)
  python manage.py createsuperuser "$@"
;;
shell)
  python manage.py shell_plus "$@"
;;
*)
  _usage
;;
esac
